#!/bin/bash

###############################################################################
# BeagleBone Black - I2C Interrupt Functional Test
#
# File:
#   tests/interrupt/test_i2c_irq.sh
#
# Purpose:
#   Verify I2C controller interrupt registration and activity.
#
# Tests:
#   1. I2C subsystem availability
#   2. I2C adapter detection
#   3. I2C device detection
#   4. I2C IRQ detection
#   5. IRQ counter baseline
#   6. I2C transaction
#   7. IRQ counter verification
#   8. Kernel I2C/IRQ messages
#
# Usage:
#
#   sudo ./tests/interrupt/test_i2c_irq.sh
#   sudo ./tests/interrupt/test_i2c_irq.sh 2
#   sudo ./tests/interrupt/test_i2c_irq.sh 2 0x50
#
# Arguments:
#
#   $1 = I2C bus number
#   $2 = Optional I2C slave address
#
# Example:
#
#   sudo ./tests/interrupt/test_i2c_irq.sh 2 0x50
#
# IMPORTANT:
#   I2C interrupt activity is generated by actual I2C controller
#   transactions. A valid I2C slave device should be connected.
###############################################################################

set -u

###############################################################################
# Configuration
###############################################################################

I2C_BUS="${1:-2}"
I2C_ADDRESS="${2:-}"

I2C_DEVICE="/dev/i2c-${I2C_BUS}"

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

TIMESTAMP="$(date '+%Y%m%d_%H%M%S')"

LOG_DIR="${PROJECT_ROOT}/logs/interrupt"
LOG_FILE="${LOG_DIR}/i2c_irq_${TIMESTAMP}.log"

mkdir -p "${LOG_DIR}"

###############################################################################
# Colors
###############################################################################

GREEN="\033[0;32m"
RED="\033[0;31m"
YELLOW="\033[1;33m"
NC="\033[0m"

###############################################################################
# Counters
###############################################################################

PASS=0
FAIL=0
SKIP=0

###############################################################################
# Logging Functions
###############################################################################

log()
{
    echo "$1" | tee -a "${LOG_FILE}"
}

pass()
{
    echo -e "${GREEN}[PASS]${NC} $1" | tee -a "${LOG_FILE}"
    PASS=$((PASS + 1))
}

fail()
{
    echo -e "${RED}[FAIL]${NC} $1" | tee -a "${LOG_FILE}"
    FAIL=$((FAIL + 1))
}

skip()
{
    echo -e "${YELLOW}[SKIP]${NC} $1" | tee -a "${LOG_FILE}"
    SKIP=$((SKIP + 1))
}

###############################################################################
# Root Check
###############################################################################

if [ "${EUID}" -ne 0 ]; then

    fail "This test must be run as root."

    echo
    echo "Use:"
    echo "  sudo ./tests/interrupt/test_i2c_irq.sh"

    exit 1
fi

###############################################################################
# Header
###############################################################################

log "============================================================"
log " BeagleBone Black - I2C Interrupt Test"
log "============================================================"
log "Date       : $(date)"
log "Kernel     : $(uname -r)"
log "Board      : $(tr '\0' '\n' < /proc/device-tree/model 2>/dev/null || echo Unknown)"
log "I2C Bus    : ${I2C_BUS}"
log "I2C Address: ${I2C_ADDRESS:-AUTO}"
log "Log File   : ${LOG_FILE}"
log "============================================================"
log ""

###############################################################################
# Test 1 - I2C Subsystem
###############################################################################

log "------------------------------------------------------------"
log "TEST 1: I2C subsystem"
log "------------------------------------------------------------"

if [ -d /sys/bus/i2c ] && [ -d /sys/class/i2c-adapter ]; then

    pass "Linux I2C subsystem is available."

else

    fail "Linux I2C subsystem is not available."

    exit 1
fi

###############################################################################
# Test 2 - Required Utilities
###############################################################################

log ""
log "------------------------------------------------------------"
log "TEST 2: Required utilities"
log "------------------------------------------------------------"

COMMANDS_OK=1

for CMD in i2cdetect i2cget i2cset; do

    if command -v "${CMD}" >/dev/null 2>&1; then

        log "[OK] ${CMD}"

    else

        skip "${CMD} is not installed."

        COMMANDS_OK=0

    fi

done

if [ "${COMMANDS_OK}" -eq 1 ]; then

    pass "I2C utilities are available."

fi

###############################################################################
# Test 3 - I2C Adapter Detection
###############################################################################

log ""
log "------------------------------------------------------------"
log "TEST 3: I2C adapter detection"
log "------------------------------------------------------------"

I2C_ADAPTERS="$(find /sys/class/i2c-adapter \
    -maxdepth 1 \
    -type l \
    -name 'i2c-*' \
    2>/dev/null || true)"

if [ -n "${I2C_ADAPTERS}" ]; then

    log "Detected I2C adapters:"

    echo "${I2C_ADAPTERS}" | \
        tee -a "${LOG_FILE}"

    pass "I2C adapter(s) detected."

else

    fail "No I2C adapters detected."

    exit 1
fi

###############################################################################
# Test 4 - Selected I2C Bus
###############################################################################

log ""
log "------------------------------------------------------------"
log "TEST 4: Selected I2C bus"
log "------------------------------------------------------------"

if [ -e "${I2C_DEVICE}" ]; then

    pass "I2C device ${I2C_DEVICE} exists."

else

    fail "I2C device ${I2C_DEVICE} does not exist."

    log ""
    log "Available I2C devices:"

    ls -l /dev/i2c-* 2>/dev/null | \
        tee -a "${LOG_FILE}" || true

    exit 1
fi

###############################################################################
# Test 5 - I2C Device Scan
###############################################################################

log ""
log "------------------------------------------------------------"
log "TEST 5: I2C device scan"
log "------------------------------------------------------------"

if command -v i2cdetect >/dev/null 2>&1; then

    log "Scanning ${I2C_DEVICE}..."

    if i2cdetect -y "${I2C_BUS}" 2>&1 | \
        tee -a "${LOG_FILE}"; then

        pass "I2C bus scan completed."

    else

        fail "I2C bus scan failed."

    fi

else

    skip "i2cdetect is not available."

fi

###############################################################################
# Test 6 - I2C IRQ Detection
###############################################################################

log ""
log "------------------------------------------------------------"
log "TEST 6: I2C IRQ detection"
log "------------------------------------------------------------"

I2C_IRQ_LINES="$(grep -iE \
    "i2c|omap.*i2c|twsi|adapter" \
    /proc/interrupts 2>/dev/null || true)"

if [ -n "${I2C_IRQ_LINES}" ]; then

    log "I2C-related interrupt entries:"

    echo "${I2C_IRQ_LINES}" | \
        tee -a "${LOG_FILE}"

    pass "I2C-related interrupt entry found."

else

    skip "No obvious I2C interrupt entry found."

fi

###############################################################################
# Function - Get I2C IRQ Count
###############################################################################

get_i2c_irq_count()
{
    grep -iE \
        "i2c|omap.*i2c|twsi|adapter" \
        /proc/interrupts 2>/dev/null | \
        awk '{
            for (i = 2; i <= NF; i++) {
                if ($i ~ /^[0-9]+$/)
                    sum += $i
            }
        }
        END {
            print sum + 0
        }'
}

###############################################################################
# Test 7 - IRQ Baseline
###############################################################################

log ""
log "------------------------------------------------------------"
log "TEST 7: I2C IRQ baseline"
log "------------------------------------------------------------"

IRQ_BEFORE="$(get_i2c_irq_count)"

log "I2C IRQ count before transaction: ${IRQ_BEFORE}"

if [ -n "${IRQ_BEFORE}" ]; then

    pass "I2C IRQ baseline captured."

else

    skip "Unable to determine I2C IRQ baseline."

fi

###############################################################################
# Test 8 - I2C Transaction
###############################################################################

log ""
log "------------------------------------------------------------"
log "TEST 8: I2C transaction"
log "------------------------------------------------------------"

if [ -z "${I2C_ADDRESS}" ]; then

    skip "No I2C slave address supplied."

    log ""
    log "Run with an address, for example:"
    log ""
    log "  sudo ./tests/interrupt/test_i2c_irq.sh 2 0x50"

else

    if command -v i2cget >/dev/null 2>&1; then

        ADDRESS_DEC=$((I2C_ADDRESS))

        log "Reading I2C address ${I2C_ADDRESS}"
        log "Bus: ${I2C_BUS}"

        if i2cget -y \
            "${I2C_BUS}" \
            "${ADDRESS_DEC}" \
            0x00 \
            2>&1 | tee -a "${LOG_FILE}"; then

            pass "I2C read transaction completed."

        else

            fail "I2C read transaction failed."

            log ""
            log "Possible reasons:"
            log "  - I2C slave is not connected"
            log "  - Incorrect slave address"
            log "  - SDA/SCL wiring problem"
            log "  - Missing pull-up resistors"
            log "  - Incorrect pinmux"
            log "  - Device Tree configuration"
            log "  - I2C controller disabled"

        fi

    else

        skip "i2cget is not available."

    fi

fi

###############################################################################
# Test 9 - IRQ Counter Verification
###############################################################################

log ""
log "------------------------------------------------------------"
log "TEST 9: I2C interrupt activity"
log "------------------------------------------------------------"

sleep 1

IRQ_AFTER="$(get_i2c_irq_count)"

log "I2C IRQ count after transaction: ${IRQ_AFTER}"

if [ -n "${IRQ_BEFORE}" ] && \
   [ -n "${IRQ_AFTER}" ]; then

    if [ "${IRQ_AFTER}" -gt "${IRQ_BEFORE}" ]; then

        pass "I2C interrupt counter increased."

    else

        skip "I2C interrupt counter did not increase."

        log ""
        log "Possible reasons:"
        log "  - No valid I2C transaction occurred"
        log "  - I2C slave did not respond"
        log "  - Controller is polling instead of interrupt driven"
        log "  - IRQ entry could not be mapped correctly"

    fi

else

    skip "Unable to evaluate I2C IRQ activity."

fi

###############################################################################
# Test 10 - I2C Sysfs Information
###############################################################################

log ""
log "------------------------------------------------------------"
log "TEST 10: I2C sysfs information"
log "------------------------------------------------------------"

I2C_SYSFS="/sys/class/i2c-adapter/i2c-${I2C_BUS}"

if [ -d "${I2C_SYSFS}" ]; then

    log "I2C sysfs path: ${I2C_SYSFS}"

    if [ -f "${I2C_SYSFS}/name" ]; then

        log "Adapter name: $(cat "${I2C_SYSFS}/name")"

    fi

    pass "I2C sysfs information inspected."

else

    skip "I2C sysfs entry not found."

fi

###############################################################################
# Test 11 - Kernel I2C Messages
###############################################################################

log ""
log "------------------------------------------------------------"
log "TEST 11: I2C kernel messages"
log "------------------------------------------------------------"

log "Recent I2C-related kernel messages:"

dmesg 2>/dev/null | \
    grep -iE "i2c|omap.*i2c|twsi" | \
    tail -50 | \
    tee -a "${LOG_FILE}" || true

pass "I2C kernel-log inspection completed."

###############################################################################
# Summary
###############################################################################

log ""
log "============================================================"
log " I2C IRQ TEST SUMMARY"
log "============================================================"

echo -e "${GREEN}PASS : ${PASS}${NC}" | tee -a "${LOG_FILE}"
echo -e "${RED}FAIL : ${FAIL}${NC}" | tee -a "${LOG_FILE}"
echo -e "${YELLOW}SKIP : ${SKIP}${NC}" | tee -a "${LOG_FILE}"

log ""
log "I2C Bus       : ${I2C_BUS}"
log "I2C Device    : ${I2C_DEVICE}"
log "I2C Address   : ${I2C_ADDRESS:-NOT PROVIDED}"
log "IRQ Before    : ${IRQ_BEFORE:-UNKNOWN}"
log "IRQ After     : ${IRQ_AFTER:-UNKNOWN}"

log ""
log "Test log:"
log "${LOG_FILE}"

###############################################################################
# Final Result
###############################################################################

if [ "${FAIL}" -eq 0 ]; then

    log ""
    log "RESULT: PASS"

    exit 0

else

    log ""
    log "RESULT: FAIL"

    exit 1

fi
