#!/bin/bash

###############################################################################
# BeagleBone Black - SPI Interrupt Functional Test
#
# File:
#   tests/interrupt/test_spi_irq.sh
#
# Purpose:
#   Verify SPI controller interrupt registration and interrupt activity.
#
# Tests:
#   1. SPI subsystem availability
#   2. SPI controller detection
#   3. SPI device detection
#   4. SPI IRQ detection
#   5. IRQ counter baseline
#   6. SPI transaction
#   7. IRQ counter verification
#   8. Kernel SPI/IRQ messages
#
# Usage:
#
#   sudo ./tests/interrupt/test_spi_irq.sh
#   sudo ./tests/interrupt/test_spi_irq.sh /dev/spidev1.0
#   sudo ./tests/interrupt/test_spi_irq.sh /dev/spidev1.0 1000000
#
# Arguments:
#
#   $1 = SPI device
#   $2 = SPI speed in Hz
#
# Example:
#
#   sudo ./tests/interrupt/test_spi_irq.sh /dev/spidev1.0 1000000
#
# IMPORTANT:
#   SPI interrupt activity is generated by an actual SPI transaction.
#   A valid SPI device or loopback connection is recommended.
###############################################################################

set -u

###############################################################################
# Configuration
###############################################################################

SPI_DEVICE="${1:-}"
SPI_SPEED="${2:-1000000}"
SPI_BITS="${3:-8}"

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

TIMESTAMP="$(date '+%Y%m%d_%H%M%S')"

LOG_DIR="${PROJECT_ROOT}/logs/interrupt"
LOG_FILE="${LOG_DIR}/spi_irq_${TIMESTAMP}.log"

mkdir -p "${LOG_DIR}"

###############################################################################
# Colors
###############################################################################

GREEN="\033[0;32m"
RED="\033[0;31m"
YELLOW="\033[1;33m"
NC="\033[0m"

###############################################################################
# Counters
###############################################################################

PASS=0
FAIL=0
SKIP=0

###############################################################################
# Logging Functions
###############################################################################

log()
{
    echo "$1" | tee -a "${LOG_FILE}"
}

pass()
{
    echo -e "${GREEN}[PASS]${NC} $1" | tee -a "${LOG_FILE}"
    PASS=$((PASS + 1))
}

fail()
{
    echo -e "${RED}[FAIL]${NC} $1" | tee -a "${LOG_FILE}"
    FAIL=$((FAIL + 1))
}

skip()
{
    echo -e "${YELLOW}[SKIP]${NC} $1" | tee -a "${LOG_FILE}"
    SKIP=$((SKIP + 1))
}

###############################################################################
# Root Check
###############################################################################

if [ "${EUID}" -ne 0 ]; then

    fail "This test must be run as root."

    echo
    echo "Use:"
    echo "  sudo ./tests/interrupt/test_spi_irq.sh"

    exit 1
fi

###############################################################################
# Header
###############################################################################

log "============================================================"
log " BeagleBone Black - SPI Interrupt Test"
log "============================================================"
log "Date       : $(date)"
log "Kernel     : $(uname -r)"
log "Board      : $(tr '\0' '\n' < /proc/device-tree/model 2>/dev/null || echo Unknown)"
log "SPI Device : ${SPI_DEVICE:-AUTO}"
log "SPI Speed  : ${SPI_SPEED} Hz"
log "SPI Bits   : ${SPI_BITS}"
log "Log File   : ${LOG_FILE}"
log "============================================================"
log ""

###############################################################################
# Test 1 - SPI Subsystem
###############################################################################

log "------------------------------------------------------------"
log "TEST 1: SPI subsystem"
log "------------------------------------------------------------"

if [ -d /sys/bus/spi ] && [ -d /sys/class/spi_master ]; then

    pass "Linux SPI subsystem is available."

else

    fail "Linux SPI subsystem is not available."

    exit 1
fi

###############################################################################
# Test 2 - SPI Controller Detection
###############################################################################

log ""
log "------------------------------------------------------------"
log "TEST 2: SPI controller detection"
log "------------------------------------------------------------"

SPI_CONTROLLERS="$(find /sys/class/spi_master \
    -maxdepth 1 \
    -type l \
    -name 'spi*' \
    2>/dev/null || true)"

if [ -n "${SPI_CONTROLLERS}" ]; then

    log "Detected SPI controllers:"

    echo "${SPI_CONTROLLERS}" | \
        tee -a "${LOG_FILE}"

    pass "SPI controller(s) detected."

else

    fail "No SPI controllers detected."

    exit 1
fi

###############################################################################
# Test 3 - SPI Device Detection
###############################################################################

log ""
log "------------------------------------------------------------"
log "TEST 3: SPI device detection"
log "------------------------------------------------------------"

SPI_DEVICES="$(find /sys/bus/spi/devices \
    -maxdepth 1 \
    -type l \
    2>/dev/null || true)"

if [ -n "${SPI_DEVICES}" ]; then

    log "Registered SPI devices:"

    echo "${SPI_DEVICES}" | \
        tee -a "${LOG_FILE}"

    pass "SPI device(s) detected."

else

    skip "No SPI slave devices registered."

fi

###############################################################################
# Test 4 - SPI Device Node
###############################################################################

log ""
log "------------------------------------------------------------"
log "TEST 4: SPI device-node verification"
log "------------------------------------------------------------"

ACTIVE_SPI=0

if [ -z "${SPI_DEVICE}" ]; then

    skip "No SPI device supplied."

    log ""
    log "Available SPI devices:"

    find /dev \
        -maxdepth 1 \
        -type c \
        -name 'spidev*' \
        2>/dev/null | \
        tee -a "${LOG_FILE}"

else

    if [ ! -e "${SPI_DEVICE}" ]; then

        fail "SPI device ${SPI_DEVICE} does not exist."

    elif [ ! -c "${SPI_DEVICE}" ]; then

        fail "${SPI_DEVICE} is not a character device."

    else

        pass "SPI device ${SPI_DEVICE} exists."

        ACTIVE_SPI=1

    fi

fi

###############################################################################
# Function - Get SPI IRQ Count
###############################################################################

get_spi_irq_count()
{
    grep -iE \
        "spi|mcspi|omap.*spi|spi_master" \
        /proc/interrupts 2>/dev/null | \
        awk '{
            for (i = 2; i <= NF; i++) {
                if ($i ~ /^[0-9]+$/)
                    sum += $i
            }
        }
        END {
            print sum + 0
        }'
}

###############################################################################
# Test 5 - SPI IRQ Detection
###############################################################################

log ""
log "------------------------------------------------------------"
log "TEST 5: SPI IRQ detection"
log "------------------------------------------------------------"

SPI_IRQ_LINES="$(grep -iE \
    "spi|mcspi|omap.*spi|spi_master" \
    /proc/interrupts 2>/dev/null || true)"

if [ -n "${SPI_IRQ_LINES}" ]; then

    log "SPI-related interrupt entries:"

    echo "${SPI_IRQ_LINES}" | \
        tee -a "${LOG_FILE}"

    pass "SPI-related interrupt entry found."

else

    skip "No obvious SPI interrupt entry found."

fi

###############################################################################
# Test 6 - IRQ Baseline
###############################################################################

log ""
log "------------------------------------------------------------"
log "TEST 6: SPI IRQ baseline"
log "------------------------------------------------------------"

IRQ_BEFORE="$(get_spi_irq_count)"

log "SPI IRQ count before transaction: ${IRQ_BEFORE}"

if [ -n "${IRQ_BEFORE}" ]; then

    pass "SPI IRQ baseline captured."

else

    skip "Unable to determine SPI IRQ baseline."

fi

###############################################################################
# Test 7 - SPI Transaction
###############################################################################

log ""
log "------------------------------------------------------------"
log "TEST 7: SPI transaction"
log "------------------------------------------------------------"

if [ "${ACTIVE_SPI}" -eq 1 ]; then

    if command -v spidev_test >/dev/null 2>&1; then

        log "Starting SPI transaction..."

        log "Device : ${SPI_DEVICE}"
        log "Speed  : ${SPI_SPEED} Hz"
        log "Bits   : ${SPI_BITS}"

        if spidev_test \
            -D "${SPI_DEVICE}" \
            -s "${SPI_SPEED}" \
            -b "${SPI_BITS}" \
            2>&1 | tee -a "${LOG_FILE}"; then

            pass "SPI transaction completed."

        else

            fail "SPI transaction failed."

        fi

    else

        skip "spidev_test is not installed."

        log ""
        log "Install/build spidev_test to perform an SPI transaction."

    fi

else

    skip "SPI transaction skipped because no device was selected."

fi

###############################################################################
# Test 8 - IRQ Counter Verification
###############################################################################

log ""
log "------------------------------------------------------------"
log "TEST 8: SPI interrupt activity"
log "------------------------------------------------------------"

sleep 1

IRQ_AFTER="$(get_spi_irq_count)"

log "SPI IRQ count after transaction: ${IRQ_AFTER}"

if [ -n "${IRQ_BEFORE}" ] && \
   [ -n "${IRQ_AFTER}" ]; then

    if [ "${IRQ_AFTER}" -gt "${IRQ_BEFORE}" ]; then

        pass "SPI interrupt counter increased."

    else

        skip "SPI interrupt counter did not increase."

        log ""
        log "Possible reasons:"
        log "  - SPI transaction was not performed"
        log "  - SPI controller is not using an IRQ"
        log "  - SPI driver is not configured correctly"
        log "  - Incorrect Device Tree configuration"
        log "  - SPI controller is disabled"
        log "  - SPI device is not connected"

    fi

else

    skip "Unable to evaluate SPI IRQ activity."

fi

###############################################################################
# Test 9 - SPI Sysfs Information
###############################################################################

log ""
log "------------------------------------------------------------"
log "TEST 9: SPI sysfs information"
log "------------------------------------------------------------"

if [ -n "${SPI_DEVICES}" ]; then

    for DEVICE_PATH in ${SPI_DEVICES}; do

        log ""
        log "SPI device: ${DEVICE_PATH}"

        if [ -f "${DEVICE_PATH}/modalias" ]; then

            log "  modalias: $(cat "${DEVICE_PATH}/modalias" 2>/dev/null)"

        fi

        if [ -f "${DEVICE_PATH}/uevent" ]; then

            log "  uevent:"

            cat "${DEVICE_PATH}/uevent" 2>/dev/null | \
                tee -a "${LOG_FILE}"

        fi

    done

    pass "SPI sysfs information inspected."

else

    skip "No SPI devices available for sysfs inspection."

fi

###############################################################################
# Test 10 - Interrupt Table
###############################################################################

log ""
log "------------------------------------------------------------"
log "TEST 10: Interrupt table"
log "------------------------------------------------------------"

log "Current SPI-related interrupt entries:"

grep -iE \
    "spi|mcspi|omap.*spi|spi_master" \
    /proc/interrupts 2>/dev/null | \
    tee -a "${LOG_FILE}" || true

pass "Interrupt table inspection completed."

###############################################################################
# Test 11 - Kernel SPI Messages
###############################################################################

log ""
log "------------------------------------------------------------"
log "TEST 11: SPI kernel messages"
log "------------------------------------------------------------"

log "Recent SPI-related kernel messages:"

dmesg 2>/dev/null | \
    grep -iE "spi|spidev|mcspi|omap.*spi" | \
    tail -50 | \
    tee -a "${LOG_FILE}" || true

pass "SPI kernel-log inspection completed."

###############################################################################
# Summary
###############################################################################

log ""
log "============================================================"
log " SPI IRQ TEST SUMMARY"
log "============================================================"

echo -e "${GREEN}PASS : ${PASS}${NC}" | tee -a "${LOG_FILE}"
echo -e "${RED}FAIL : ${FAIL}${NC}" | tee -a "${LOG_FILE}"
echo -e "${YELLOW}SKIP : ${SKIP}${NC}" | tee -a "${LOG_FILE}"

log ""
log "SPI Device : ${SPI_DEVICE:-NOT PROVIDED}"
log "Speed      : ${SPI_SPEED} Hz"
log "Bits       : ${SPI_BITS}"
log "IRQ Before : ${IRQ_BEFORE:-UNKNOWN}"
log "IRQ After  : ${IRQ_AFTER:-UNKNOWN}"

log ""
log "Test log:"
log "${LOG_FILE}"

###############################################################################
# Final Result
###############################################################################

if [ "${FAIL}" -eq 0 ]; then

    log ""
    log "RESULT: PASS"

    exit 0

else

    log ""
    log "RESULT: FAIL"

    exit 1

fi
